//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlHoras
    {
        public int IdControl { get; set; }
        public int IdEmpleado { get; set; }
        public int Semana { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> Lunes { get; set; }
        public Nullable<int> Martes { get; set; }
        public Nullable<int> Miercoles { get; set; }
        public Nullable<int> Jueves { get; set; }
        public Nullable<int> Viernes { get; set; }
        public Nullable<int> Sabado { get; set; }
        public int TotalHoras { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
