//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.ControlHoras = new HashSet<ControlHoras>();
            this.CuentaEmpleado = new HashSet<CuentaEmpleado>();
            this.PagoSemanal = new HashSet<PagoSemanal>();
        }
    
        public int IdEmpleado { get; set; }
        public int IdCategoria { get; set; }
        public string Nombre { get; set; }
        public decimal Telefono { get; set; }
        public string Direccion { get; set; }
        public string Estado { get; set; }
        public Nullable<int> IdCuenta { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlHoras> ControlHoras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentaEmpleado> CuentaEmpleado { get; set; }
        public virtual CuentaEmpleado CuentaEmpleado1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagoSemanal> PagoSemanal { get; set; }
    }
}
