//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaIngreso
    {
        public int NumeroFacturaIngreso { get; set; }
        public int NumeroFactura { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Semana { get; set; }
        public string Descripcion { get; set; }
        public decimal Total { get; set; }
    
        public virtual Factura Factura { get; set; }
    }
}
