//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_ConstruccionesEntities : DbContext
    {
        public BD_ConstruccionesEntities()
            : base("name=BD_ConstruccionesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<ControlHoras> ControlHoras { get; set; }
        public virtual DbSet<CuentaEmpleado> CuentaEmpleado { get; set; }
        public virtual DbSet<DetalleFactura> DetalleFactura { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Factura> Factura { get; set; }
        public virtual DbSet<FacturaIngreso> FacturaIngreso { get; set; }
        public virtual DbSet<modulo> modulo { get; set; }
        public virtual DbSet<PagoSemanal> PagoSemanal { get; set; }
        public virtual DbSet<permisosDeRol> permisosDeRol { get; set; }
        public virtual DbSet<RetiroCuentaEmpleado> RetiroCuentaEmpleado { get; set; }
        public virtual DbSet<rolAsignadoAUsuario> rolAsignadoAUsuario { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    }
}
