//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class permisosDeRol
    {
        public int idrol { get; set; }
        public int idventana { get; set; }
        public Nullable<int> insertar { get; set; }
        public Nullable<int> modificar { get; set; }
        public Nullable<int> eliminar { get; set; }
        public Nullable<int> consultar { get; set; }
    
        public virtual roles roles { get; set; }
        public virtual ventanas ventanas { get; set; }
    }
}
